name: postgres-stack
services:
  postgres:
    image: postgres:17@sha256:6a2fb9aaf22abf4c5aeeeb8fcd12dfb57b7531d8d5196f90cfe0ce3f68c4c13f
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - /volume2/dockers/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    mem_limit: 1g
    # cpus: 2.0
    networks:
      - postgres-stack
    # Synology Container Manager uses as default log.db, however, due my fluentbit flow
    # I am reading logs from json files, flagging it here in the compose to force Synlogy 
    # to save logs the way I need them.
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:50700ac17936d0227f9e3e4bb086a91efb67064debc4b4737c35545bf1564088
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8280:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-stack
    # Synology Container Manager uses as default log.db, however, due my fluentbit flow
    # I am reading logs from json files, flagging it here in the compose to force Synlogy 
    # to save logs the way I need them.
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  pgadmin_data:

networks:
  postgres-stack: